# This workflow will check if code is formatted using Black

name: Check Code Format

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  BlackFormatCheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
